param(
# Host-mapped OptimusDB API base URL
    [string]$OptimusDbBaseUrl = "http://localhost:18001"
)

# Final URL we will POST to (same as in OptimusDBProxy: base_url + /swarmkb/command)
$CommandUrl = "$OptimusDbBaseUrl/swarmkb/command"

Write-Host "Using OptimusDB endpoint: $CommandUrl"
Write-Host ""

function Escape-SqlLiteral {
    param([string]$value)
    if ($null -eq $value) { return "" }
    return $value.Replace("'", "''")
}

# -------------------------------------------------------------------
# Define all 30 tables (datasets) as logical metadata
# -------------------------------------------------------------------
$tables = @(
# 1) Average Energy Coefficient (AEC)
    @{
        name        = "kpi_aec"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Average Energy Coefficient: ratio between gross energy produced and volume of water used at average head condition."
        tags        = @("kpi","hydro","aec","annex-b")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 2) Available Hours (AH)
    @{
        name        = "kpi_ah_available_hours"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Number of hours a unit was in the available state (AH = RSH + SH + SHNG)."
        tags        = @("kpi","availability","ah","hydro","wind","solar","bess")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 3) Attempted Unit Start (AUS)
    @{
        name        = "kpi_aus_attempted_unit_start"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Attempted unit starts: action of trying to bring a unit from shutdown to in-service, including GAUS and NGAUS."
        tags        = @("kpi","operations","startup","aus")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 4) Energy Consumption for Pumping (CP)
    @{
        name        = "kpi_cp_pumping_consumption"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Energy used by pumping storage plants when in pumping mode (CP)."
        tags        = @("kpi","pumped-storage","cp","hydro")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 5) Deliverable Producible Energy (DPE)
    @{
        name        = "kpi_dpe_deliverable_producible_energy"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Maximum energy producible under optimum conditions with flowed resource (DPE = GAAP + LP)."
        tags        = @("kpi","resource","dpe")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 6) Delta Reservoir Storage (DS)
    @{
        name        = "kpi_ds_delta_reservoir_storage"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Variation of resource stored in reservoirs; not counted as Lost Production."
        tags        = @("kpi","hydro","reservoir","ds")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 7) Deactivated Hours (DSH)
    @{
        name        = "kpi_dsh_deactivated_hours"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Number of hours a unit was in the inactive state."
        tags        = @("kpi","availability","dsh")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 8) Forced Outage Hours (FOH)
    @{
        name        = "kpi_foh_forced_outage_hours"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Number of hours a unit was in an unplanned forced outage state."
        tags        = @("kpi","forced-outage","foh","wind","solar")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 9) Gross Actual Production (GAAP)
    @{
        name        = "kpi_gaap_gross_actual_production"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Gross energy generated by a unit in each period (GAAP = NAAP + self-consumption + losses)."
        tags        = @("kpi","production","gaap")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 10) Gross Available Capacity (GAC)
    @{
        name        = "kpi_gac_gross_available_capacity"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Maximum gross capacity available, considering equipment and ambient limitations."
        tags        = @("kpi","capacity","gac")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 11) Gross Available Production (GAP)
    @{
        name        = "kpi_gap_gross_available_production"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Energy that could have been generated if operated at GAC (GAP = PH x GAC)."
        tags        = @("kpi","production","gap")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 12) Gross Maximum Capacity (GMC)
    @{
        name        = "kpi_gmc_gross_maximum_capacity"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Gross maximum capacity obtainable under test conditions, independent of temporary deratings."
        tags        = @("kpi","capacity","gmc")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 13) Gross Maximum Production (GMP)
    @{
        name        = "kpi_gmp_gross_maximum_production"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Energy that could have been produced if operated at GMC (GMP = PH x GMC)."
        tags        = @("kpi","production","gmp")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 14) Gross Maximum Pumping Capacity (GMPC)
    @{
        name        = "kpi_gmpc_gross_maximum_pumping_capacity"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Gross maximum capacity that a unit can absorb from the grid in pumping mode."
        tags        = @("kpi","pumped-storage","capacity","gmpc")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 15) Tilted Irradiance (Irr)
    @{
        name        = "kpi_irr_tilted_irradiance"
        schema      = "annexb_kpis"
        database    = "renewables_om"
        description = "Tilted irradiance on PV modules considering tracker tilt angle."
        tags        = @("kpi","solar","irradiance","irr")
        owners      = @(@{ email = "energy.dataowner@company.com" })
    }

# 16) AvailabilityData
    @{
        name        = "bax_availabilitydata"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "AvailabilityData: log-interval availability samples per plant with T0..T30 fields and value."
        tags        = @("bax","availability","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 17) AvailabilityLog
    @{
        name        = "bax_availabilitylog"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "AvailabilityLog: main and substatus transitions for each plant with timestamps and virtual buckets."
        tags        = @("bax","availability","events")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 18) BaxMetadata
    @{
        name        = "bax_metadata"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "BaxMetadata: generic property name/value pairs for devices and events."
        tags        = @("bax","metadata","key-value")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 19) CategorizedEvent
    @{
        name        = "bax_categorized_event"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "CategorizedEvent: event categorizations with duration, device, category sets and acknowledgment flags."
        tags        = @("bax","events","categorization")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 20) CategorizedEventChangeLog
    @{
        name        = "bax_categorized_event_changelog"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "Change log for categorized events, tracking action type, input/output events and user."
        tags        = @("bax","events","audit")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 21) DeviceView
    @{
        name        = "bax_deviceview"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "DeviceView: device inventory with coordinates, hierarchy path, technology, and provider data."
        tags        = @("bax","inventory","devices")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 22) ELog_Data
    @{
        name        = "bax_elog_data"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "ELog_Data: environmental logger data (irradiance, temperatures, power supply) with log intervals."
        tags        = @("bax","logger","environment","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 23) ES_CURRENTS
    @{
        name        = "bax_es_currents"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "ES_CURRENTS: electrical currents per phase (L1-L3) aggregated by log interval and plant."
        tags        = @("bax","electrical","currents","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 24) ES_VOLTGES
    @{
        name        = "bax_es_voltges"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "ES_VOLTGES: voltage per phase (L1-L3) with avg/max/min/std fields and timestamps."
        tags        = @("bax","electrical","voltages","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 25) InverterData
    @{
        name        = "bax_inverterdata"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "InverterData: per-inverter production, power, temperatures, radiation and operation hours."
        tags        = @("bax","inverter","production","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 26) MeteoData
    @{
        name        = "bax_meteodata"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "MeteoData: site-level meteo timeseries including air and module temperature and radiation."
        tags        = @("bax","meteo","weather","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 27) MeteringUnitData
    @{
        name        = "bax_meteringunitdata"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "MeteringUnitData: timeseries per metering unit device and timestamp."
        tags        = @("bax","metering","timeseries")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 28) NpParkEvent
    @{
        name        = "bax_np_parkevent"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "NpParkEvent: high-level park events with duration, status code and localization key."
        tags        = @("bax","events","park")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 29) Plant
    @{
        name        = "bax_plant"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "Plant: plant master data including commissioning date, nominal power, hub height and power curve ids."
        tags        = @("bax","masterdata","plant")
        owners      = @(@{ email = "bax.integration@company.com" })
    }

# 30) PowerCurve / PowerCurvePoint
    @{
        name        = "bax_powercurve"
        schema      = "baxlocation_sp_hl1bn"
        database    = "baxenergy"
        description = "PowerCurve and PowerCurvePoint data describing turbine power vs wind speed sectors and points."
        tags        = @("bax","powercurve","performance")
        owners      = @(@{ email = "bax.integration@company.com" })
    }
)

# -------------------------------------------------------------------
# Insert each table into datacatalog via sqldml → /swarmkb/command
# -------------------------------------------------------------------
foreach ($t in $tables) {
    $id         = [guid]::NewGuid().ToString()
    $createdBy  = $t.owners[0].email
    $tagsStr    = ($t.tags -join ",")
    $schemaEsc  = Escape-SqlLiteral $t.schema
    $dbEsc      = Escape-SqlLiteral $t.database
    $nameEsc    = Escape-SqlLiteral $t.name
    $descEsc    = Escape-SqlLiteral $t.description
    $tagsEsc    = Escape-SqlLiteral $tagsStr
    $createdEsc = Escape-SqlLiteral $createdBy

    $sql = @"
INSERT INTO datacatalog (
  _id,
  author,
  metadata_type,
  component,
  behaviour,
  relationships,
  associated_id,
  name,
  description,
  tags,
  status,
  created_by,
  related_ids,
  priority,
  scheduling_info,
  sla_constraints,
  ownership_details,
  audit_trail
) VALUES (
  '$id',
  '$createdEsc',
  '$schemaEsc',
  '$dbEsc',
  'dataset_registration',
  '',
  '$id',
  '$nameEsc',
  '$descEsc',
  '$tagsEsc',
  'active',
  '$createdEsc',
  '',
  'normal',
  '',
  '',
  '$createdEsc',
  'created via PowerShell seeding script'
);
"@

    $payload = @{
        method          = @{ argcnt = 2; cmd = "sqldml" }
        args            = @("dummy1", "dummy2")
        dstype          = "dsswres"
        sqldml          = $sql
        graph_traversal = @(@{})
        criteria        = @()
    }

    $json = $payload | ConvertTo-Json -Depth 6

    Write-Host "Inserting dataset '$($t.name)' (schema=$($t.schema), db=$($t.database))..."

    try {
        # IMPORTANT: POST, not PUT
        $response = Invoke-RestMethod -Method Post -Uri $CommandUrl -ContentType "application/json" -Body $json
        Write-Host "  --> OK" -ForegroundColor Green
    }
    catch {
        Write-Warning "  --> Failed: $($_.Exception.Message)"
    }

    Write-Host ""
}

Write-Host "Done seeding datacatalog."
